"""
Eviction Data Compiler

This script loads and cleans Eviction Lab data, performs spatial joins,
and pushes aggregated results to Supabase. It also determines the latest
complete month of data and updates the frontend JavaScript config files.

PIPELINE:
1. Load Eviction Lab data:
   a. el_master.csv — compiled historical record (already cleaned, fast to load)
   b. Parquet files in From_EL/ — raw EL format, cleaned on load
   c. Raw EL CSVs in From_EL/ with xcasenum column — cleaned on load
2. Deduplicate by case_id, filter to 2019-01+, export updated el_master.csv
3. Perform spatial joins to tracts, hexagons, schools, and cities
4. Load renter occupied housing units data for filing rate calculation
5. Aggregate eviction counts and filing rates by geography and month
6. Determine MAX_DATE (latest month with apparently complete data)
7. Update frontend config files (js/config*.js) with new MAX_DATE/DEFAULT_DATE
8. Push aggregated data to Supabase tables

MONTHLY WORKFLOW:
1. Drop new EL file (parquet or CSV) into From_EL/
2. Run this script
   - el_master.csv is updated automatically
   - Raw EL file is deleted automatically
   - git commit + push happens automatically (if Supabase succeeded)

Data Sources:
- Eviction Lab: ./From_EL/  (parquet or raw EL CSVs with xcasenum column)
- Compiled master: ./From_EL/el_master.csv (auto-generated, cleaned, deduplicated)

Spatial Joins (high-res GeoJSON in data-hidden/ for accuracy):
- Tracts:   region_tracts_hires.geojson
- Schools:  region_schools_hires.geojson
- Hexagons: region_hex.geojson (in data/, H3 structure doesn't need simplification)

County Aggregation:
- Derived from tract data (county FIPS = first 5 chars of tract GEOID)
- Ensures perfect alignment: sum of tract totals = county total

Frontend Config Update:
- MAX_DATE:     latest month with >= 70% of trailing average filing count
- DEFAULT_DATE: 12 months prior to MAX_DATE

Output:
- Updated el_master.csv in From_EL/
- Updated js/config*.js files
- Aggregated data pushed to Supabase
"""

import os
import re
import uuid
import math
import subprocess
from datetime import datetime
from pathlib import Path

import pandas as pd
import geopandas as gpd
from shapely.geometry import Point
from supabase import create_client, Client


# Load environment variables from .env file
def load_env_file(env_path):
    """Load environment variables from .env file if it exists."""
    if env_path.exists():
        with open(env_path, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    os.environ[key.strip()] = value.strip()


# =============================================================================
# CONFIGURATION
# =============================================================================

# Directory paths (relative to this script's location)
SCRIPT_DIR   = Path(__file__).parent
DATA_DIR     = SCRIPT_DIR.parent.parent / "data"   # ../../data/
PROJECT_ROOT = SCRIPT_DIR.parent.parent            # project root (where js/ lives)

# Load .env file if it exists
load_env_file(SCRIPT_DIR / ".env")

# Eviction Lab data directory
EVICTION_LAB_DIR = SCRIPT_DIR / "From_EL"

# Compiled master CSV (auto-generated by this script)
EL_MASTER_PATH = EVICTION_LAB_DIR / "el_master.csv"

# Files to skip when scanning From_EL/ for raw EL data
EL_SKIP_FILES = {'el_master.csv', 'all_cobb_props.csv', 'cobb_unmatched_addresses.csv'}

# Accuracy types to exclude from raw EL data (low-quality geocodes)
EL_ACCURACY_EXCLUSION = ['place', 'point', 'state', 'intersection', 'county']

# GeoJSON files for spatial joins (high-res versions in data-hidden/ for accuracy)
DATA_HIDDEN_DIR = SCRIPT_DIR.parent  # data-hidden/
GEOJSON_HEX     = DATA_DIR / "region_hex.geojson"               # H3 structure stays in data/
GEOJSON_SCHOOLS = DATA_HIDDEN_DIR / "region_schools_hires.geojson"
GEOJSON_TRACTS  = DATA_HIDDEN_DIR / "region_tracts_hires.geojson"
GEOJSON_CITIES  = DATA_DIR / "region_cities.geojson"

# County FIPS to name mapping (first 5 digits of tract GEOID = state + county FIPS)
COUNTY_FIPS_TO_NAME = {
    '13063': 'Clayton',
    '13067': 'Cobb',
    '13089': 'DeKalb',
    '13121': 'Fulton',
    '13135': 'Gwinnett',
}

# Renter Occupied Housing Units files (for filing rate calculation)
ROCC_DIR         = SCRIPT_DIR.parent  # data-hidden/
ROCC_HEX_PATH    = ROCC_DIR / "ROcc_HUs_hex.csv"
ROCC_TRACT_PATH  = ROCC_DIR / "ROcc_HUs_tract.csv"
ROCC_SCHOOL_PATH = ROCC_DIR / "ROcc_HUs_school.csv"
ROCC_CITY_PATH   = ROCC_DIR / "ROcc_HUs_city.csv"

# Supabase configuration (loaded from .env file)
SUPABASE_URL = os.environ.get("SUPABASE_URL", "")
SUPABASE_KEY = os.environ.get("SUPABASE_KEY", "")

# Processing options — set to False when ready to push to Supabase
SKIP_SUPABASE = False


# =============================================================================
# EVICTION LAB DATA LOADING
# =============================================================================

def clean_eviction_lab_raw(df: pd.DataFrame, source_label: str = "") -> pd.DataFrame:
    """
    Clean raw Eviction Lab format data (parquet or raw EL CSV).

    Applies the filtering logic from the EL analysis notebook:
    - Non-commercial filings only
    - Non-EL-duplicate filings only
    - Valid geocoding: non-null lat, not low-quality accuracy type

    Derives county_name from xcourtcofips using COUNTY_FIPS_TO_NAME.

    Returns DataFrame with columns: case_id, file_date, county_name, lat, lon
    """
    label = f"[{source_label}] " if source_label else ""
    print(f"  {label}Raw records: {len(df):,}")

    # Non-commercial filings only
    if 'commercial' in df.columns:
        df = df[df['commercial'] == False]

    # Drop EL-flagged duplicates
    if 'dup' in df.columns:
        df = df[df['dup'] == False]

    # Require valid geocoding (non-null latitude)
    if 'GEOID.latitude' in df.columns:
        df = df[df['GEOID.latitude'].notna()]

    # Exclude low-quality accuracy types
    if 'GEOID.accuracy_type' in df.columns:
        df = df[~df['GEOID.accuracy_type'].isin(EL_ACCURACY_EXCLUSION)]

    # Derive county_name from full state+county FIPS (e.g. 13121 → 'Fulton')
    if 'xcourtcofips' in df.columns:
        df = df.copy()
        df['county_name'] = (
            df['xcourtcofips'].astype(str).str.zfill(5).map(COUNTY_FIPS_TO_NAME)
        )

    # Rename to standard column names
    df = df.rename(columns={
        'xcasenum':        'case_id',
        'xfiledate':       'file_date',
        'GEOID.longitude': 'lon',
        'GEOID.latitude':  'lat',
    })

    # Return only the standard columns we need downstream
    keep = [c for c in ['case_id', 'file_date', 'county_name', 'lat', 'lon'] if c in df.columns]
    df = df[keep]

    print(f"  {label}After cleaning: {len(df):,} records")
    return df


def load_eviction_lab_data() -> pd.DataFrame:
    """
    Load all Eviction Lab eviction data.

    Load order:
    1. el_master.csv — compiled historical record (already cleaned)
    2. Parquet files in From_EL/ — raw EL format, cleaned on load
    3. Raw EL CSVs in From_EL/ — detected by xcasenum column, cleaned on load

    After combining:
    - Deduplicates by case_id (handles EL's 6-month lookback overlaps)
    - Filters to filemonth >= 2019-01
    - Exports updated el_master.csv for fast loading next run

    Returns standardized DataFrame with columns:
      case_id, file_date, county_name, lat, lon, filemonth
    """
    print(f"\nLoading Eviction Lab data from: {EVICTION_LAB_DIR}")
    all_dfs = []
    new_el_files = []  # Raw EL files loaded this run — deleted after master is updated

    # 1. Load master CSV (already cleaned — load as-is)
    if EL_MASTER_PATH.exists():
        master_df = pd.read_csv(EL_MASTER_PATH, low_memory=False)
        master_df['lat'] = pd.to_numeric(master_df['lat'], errors='coerce')
        master_df['lon'] = pd.to_numeric(master_df['lon'], errors='coerce')
        all_dfs.append(master_df)
        print(f"  Loaded master: {len(master_df):,} records")

    # 2. Load parquet files (raw EL format)
    for pf in sorted(EVICTION_LAB_DIR.glob("*.parquet")):
        print(f"\n  Loading parquet: {pf.name}")
        raw_df = pd.read_parquet(pf)
        all_dfs.append(clean_eviction_lab_raw(raw_df, pf.name))
        new_el_files.append(pf)

    # 3. Load raw EL CSVs — detect by xcasenum column, skip non-eviction files
    # Also handles legacy processed CSVs (case_id column, no xcasenum) for
    # backfilling historical data — only 2019 records are taken from these,
    # since 2020+ is already covered by the EL parquet/master.
    legacy_county_map = {
        'CLAYTON': 'Clayton', 'COBB': 'Cobb', 'DEKALB': 'DeKalb',
        'GWINNETT': 'Gwinnett', 'FULTON': 'Fulton',
    }
    for csv_file in sorted(EVICTION_LAB_DIR.glob("*.csv")):
        if csv_file.name in EL_SKIP_FILES:
            continue
        peek = pd.read_csv(csv_file, nrows=0)
        if 'xcasenum' in peek.columns:
            print(f"\n  Loading raw EL CSV: {csv_file.name}")
            raw_df = pd.read_csv(csv_file, low_memory=False)
            all_dfs.append(clean_eviction_lab_raw(raw_df, csv_file.name))
            new_el_files.append(csv_file)
        elif 'case_id' in peek.columns:
            print(f"\n  Loading legacy CSV (2019 records only): {csv_file.name}")
            leg_df = pd.read_csv(csv_file, low_memory=False)
            leg_df['lat'] = pd.to_numeric(leg_df['lat'], errors='coerce')
            leg_df['lon'] = pd.to_numeric(leg_df['lon'], errors='coerce')
            leg_df['file_date'] = pd.to_datetime(leg_df['file_date'], errors='coerce')
            leg_df['filemonth'] = leg_df['file_date'].apply(
                lambda x: f"{x.year}-{x.month:02d}" if pd.notna(x) else None
            )
            leg_df = leg_df[leg_df['filemonth'] < '2020-01']
            leg_df['county_name'] = leg_df['county_name'].str.upper().map(legacy_county_map)
            keep = [c for c in ['case_id', 'file_date', 'county_name', 'lat', 'lon', 'filemonth'] if c in leg_df.columns]
            leg_df = leg_df[keep]
            print(f"  [legacy] 2019 records: {len(leg_df):,}")
            all_dfs.append(leg_df)
        else:
            print(f"  Skipping (unrecognized format): {csv_file.name}")

    if not all_dfs:
        print("  No Eviction Lab data found.")
        print("  Place EL parquet or CSV files in the From_EL/ directory.")
        return pd.DataFrame()

    # 4. Combine and deduplicate by case_id
    combined = pd.concat(all_dfs, ignore_index=True)
    before = len(combined)
    combined = combined.drop_duplicates(subset=['case_id'])
    print(f"\n  Combined: {before:,} → {len(combined):,} records "
          f"({before - len(combined):,} duplicates removed)")

    # 5. Validate coordinates
    combined['lat'] = pd.to_numeric(combined['lat'], errors='coerce')
    combined['lon'] = pd.to_numeric(combined['lon'], errors='coerce')
    before = len(combined)
    combined = combined[
        combined['lat'].notna() & combined['lon'].notna() &
        (combined['lat'] != 0) & (combined['lon'] != 0)
    ]
    if before != len(combined):
        print(f"  Dropped {before - len(combined):,} records with invalid coordinates")

    # 6. Generate filemonth in "YYYY-MM" format
    combined['file_date'] = pd.to_datetime(combined['file_date'], errors='coerce')
    combined['filemonth'] = combined['file_date'].apply(
        lambda x: f"{x.year}-{x.month:02d}" if pd.notna(x) else None
    )
    combined = combined.dropna(subset=['filemonth'])

    # 7. Filter to 2019-01 and later
    before = len(combined)
    combined = combined[combined['filemonth'] >= '2019-01']
    if before != len(combined):
        print(f"  Filtered {before - len(combined):,} records before 2019-01")

    # 8. Export updated master CSV
    export_df = combined.copy()
    export_df['file_date'] = export_df['file_date'].dt.strftime('%Y-%m-%d')
    export_df.to_csv(EL_MASTER_PATH, index=False)

    print(f"\n  Updated el_master.csv: {len(export_df):,} records")
    print(f"  Date range: {combined['filemonth'].min()} → {combined['filemonth'].max()}")
    print(f"  Final records: {len(combined):,}")

    # Delete raw EL files now that el_master.csv is updated
    if new_el_files:
        print(f"\n  Cleaning up {len(new_el_files)} raw EL file(s):")
        for f in new_el_files:
            f.unlink()
            print(f"    Deleted: {f.name}")

    return combined


# =============================================================================
# SPATIAL JOINS
# =============================================================================

def create_geodataframe(df: pd.DataFrame) -> gpd.GeoDataFrame:
    """Convert DataFrame with lat/lon columns to a GeoDataFrame."""
    valid = df.dropna(subset=['lat', 'lon']).copy()
    if len(valid) == 0:
        return gpd.GeoDataFrame()
    geometry = [Point(xy) for xy in zip(valid['lon'], valid['lat'])]
    return gpd.GeoDataFrame(valid, geometry=geometry, crs="EPSG:4326")


def spatial_join_to_geography(
    evictions_gdf: gpd.GeoDataFrame,
    geography_path: Path,
    id_column: str,
    output_name: str,
) -> gpd.GeoDataFrame:
    """
    Perform a spatial join to assign evictions to geographic areas.

    Args:
        evictions_gdf:   GeoDataFrame of eviction points
        geography_path:  Path to GeoJSON file with polygons
        id_column:       Column in the geography file to use as identifier
        output_name:     Name for the output column (e.g., 'tract_id')

    Returns GeoDataFrame with the geography ID column added.
    """
    print(f"\n  Joining to: {geography_path.name}")

    if not geography_path.exists():
        print(f"    WARNING: File not found: {geography_path}")
        return evictions_gdf

    geography = gpd.read_file(geography_path)
    print(f"    Loaded {len(geography)} geographic units")

    if geography.crs != evictions_gdf.crs:
        geography = geography.to_crs(evictions_gdf.crs)

    joined = gpd.sjoin(
        evictions_gdf,
        geography[[id_column, 'geometry']],
        how='left',
        predicate='within',
    )

    if id_column in joined.columns:
        joined = joined.rename(columns={id_column: output_name})

    if 'index_right' in joined.columns:
        joined = joined.drop(columns=['index_right'])

    matched = joined[output_name].notna().sum() if output_name in joined.columns else 0
    print(f"    Matched: {matched:,} records")

    return joined


def perform_spatial_joins(df: pd.DataFrame) -> pd.DataFrame:
    """
    Perform spatial joins to tracts, hexagons, schools, and cities.

    Uses high-resolution GeoJSON files from data-hidden/ for accurate
    attribution. County aggregations are derived from tract data rather
    than a separate spatial join, ensuring perfect alignment.
    """
    print("\n" + "=" * 60)
    print("PERFORMING SPATIAL JOINS")
    print("=" * 60)

    gdf = create_geodataframe(df)

    if gdf.empty:
        print("  No geocoded records to process!")
        return df

    print(f"  Records for spatial join: {len(gdf):,}")

    gdf = spatial_join_to_geography(gdf, GEOJSON_TRACTS,  id_column='GEOID',      output_name='tract_id')
    gdf = spatial_join_to_geography(gdf, GEOJSON_HEX,     id_column='hex_id',     output_name='hex_id')
    gdf = spatial_join_to_geography(gdf, GEOJSON_SCHOOLS, id_column='ShortLabel', output_name='school_id')
    gdf = spatial_join_to_geography(gdf, GEOJSON_CITIES,  id_column='ShortLabel', output_name='city_id')

    result = pd.DataFrame(gdf.drop(columns=['geometry']))

    print(f"\n  Records outside boundaries:")
    print(f"    Outside tracts:  {result['tract_id'].isna().sum():,}")
    print(f"    Outside schools: {result['school_id'].isna().sum():,}")
    print(f"    Outside hexes:   {result['hex_id'].isna().sum():,}")
    print(f"    Outside cities:  {result['city_id'].isna().sum():,}")

    return result


# =============================================================================
# RENTER OCCUPIED HOUSING UNITS (for filing rate calculation)
# =============================================================================

def load_rocc_data() -> dict:
    """
    Load renter occupied housing unit data for all geographies.

    Returns dict with keys 'hex', 'tract', 'school', 'city', each mapping
    geography ID → ROcc_HUs count.
    """
    print("\n" + "=" * 60)
    print("LOADING RENTER OCCUPIED HOUSING UNITS DATA")
    print("=" * 60)

    rocc_data = {}
    for key, path, label in [
        ('hex',    ROCC_HEX_PATH,    'Hex'),
        ('tract',  ROCC_TRACT_PATH,  'Tract'),
        ('school', ROCC_SCHOOL_PATH, 'School'),
        ('city',   ROCC_CITY_PATH,   'City'),
    ]:
        if path.exists():
            df = pd.read_csv(path)
            rocc_col = 'ROcc_HUs' if 'ROcc_HUs' in df.columns else 'ROcc_Hus'
            rocc_data[key] = dict(zip(df['ShortLabel'].astype(str), df[rocc_col]))
            print(f"  {label} ROcc: {len(rocc_data[key]):,} records from {path.name}")
        else:
            print(f"  WARNING: {label} ROcc file not found: {path}")
            rocc_data[key] = {}

    return rocc_data


def calculate_filing_rate(df: pd.DataFrame, id_column: str, rocc_lookup: dict) -> pd.DataFrame:
    """Calculate filing rate (totalfilings / ROcc_HUs) for each row."""
    def calc_rate(row):
        geo_id = str(row[id_column])
        rocc = rocc_lookup.get(geo_id, 0)
        if rocc and rocc > 0:
            return round(row['totalfilings'] / rocc, 6)
        return None

    df['filing-rate'] = df.apply(calc_rate, axis=1)
    return df


# =============================================================================
# AGGREGATION
# =============================================================================

def aggregate_by_geography(df: pd.DataFrame, rocc_data: dict = None) -> dict:
    """
    Aggregate eviction counts by geography and month.

    Expects df to have 'filemonth' in "YYYY-MM" format.

    Returns dict of DataFrames keyed by geography type:
      tracts, hexagons, schools, cities, counties
    """
    print("\n" + "=" * 60)
    print("AGGREGATING DATA")
    print("=" * 60)

    if rocc_data is None:
        rocc_data = {'hex': {}, 'tract': {}, 'school': {}, 'city': {}}

    results = {}

    # Aggregate for each geography type
    for id_col, result_key, rocc_key, label in [
        ('tract_id',  'tracts',   'tract',  'Tract'),
        ('hex_id',    'hexagons', 'hex',    'Hexagon'),
        ('school_id', 'schools',  'school', 'School'),
        ('city_id',   'cities',   'city',   'City'),
    ]:
        if id_col not in df.columns:
            continue

        # pandas groupby drops NaN keys by default, so unmatched records are excluded
        agg = df.groupby([id_col, 'filemonth']).agg(
            totalfilings=(id_col, 'count')
        ).reset_index()

        if rocc_data.get(rocc_key):
            agg = calculate_filing_rate(agg, id_col, rocc_data[rocc_key])
            matched = agg['filing-rate'].notna().sum()
            print(f"  {label}: {len(agg):,} rows ({matched:,} with filing rates)")
        else:
            agg['filing-rate'] = None
            print(f"  {label}: {len(agg):,} rows (no ROcc data)")

        results[result_key] = agg

    # County aggregation derived from tract data for perfect alignment
    # County FIPS = first 5 digits of tract GEOID
    if 'tract_id' in df.columns:
        county_df = df[df['tract_id'].notna()].copy()
        county_df['county_fips'] = county_df['tract_id'].str[:5]
        county_df = county_df[county_df['county_fips'].isin(COUNTY_FIPS_TO_NAME)]
        county_df['county_name'] = county_df['county_fips'].map(COUNTY_FIPS_TO_NAME)
        county_agg = county_df.groupby(['county_name', 'filemonth']).agg(
            totalfilings=('county_name', 'count')
        ).reset_index()
        results['counties'] = county_agg
        print(f"  County: {len(county_agg):,} rows (derived from tract data)")

    return results


# =============================================================================
# MAX DATE DETECTION AND FRONTEND CONFIG UPDATE
# =============================================================================

def determine_max_date(aggregated_data: dict) -> str:
    """
    Determine the latest month with apparently complete filing data.

    Completeness heuristic: a month's total filings (across all counties)
    must be >= 70% of the average of the 6 months ending 3 months prior.
    The skip of 2 months before the candidate avoids polluting the reference
    window with other potentially incomplete recent months.

    The current calendar month is always excluded (never complete mid-month).
    Walks backwards up to 3 months from the most recent non-current month.
    Falls back to 3 months before the most recent if none qualify.
    """
    county_df = aggregated_data.get('counties', pd.DataFrame())
    if county_df.empty:
        tract_df = aggregated_data.get('tracts', pd.DataFrame())
        if tract_df.empty:
            # No data at all — fall back to 2 months ago
            now = datetime.now()
            m, y = now.month - 2, now.year
            if m <= 0:
                m += 12
                y -= 1
            return f"{y}-{m:02d}"
        monthly = tract_df.groupby('filemonth')['totalfilings'].sum().reset_index()
    else:
        monthly = county_df.groupby('filemonth')['totalfilings'].sum().reset_index()

    monthly = monthly.sort_values('filemonth').reset_index(drop=True)

    # Exclude current and future months
    current_month = datetime.now().strftime('%Y-%m')
    monthly = monthly[monthly['filemonth'] < current_month].reset_index(drop=True)

    if monthly.empty:
        return current_month

    counts = monthly['totalfilings'].tolist()
    months = monthly['filemonth'].tolist()

    if len(months) <= 4:
        return months[-1]

    print(f"  Evaluating completeness (most recent months first):")

    for i in range(len(months) - 1, max(len(months) - 4, -1), -1):
        # Reference window: 6 months ending 3 months before month[i]
        ref_end   = max(0, i - 2)
        ref_start = max(0, ref_end - 6)

        if ref_end <= ref_start:
            print(f"    {months[i]}: insufficient history, accepting")
            return months[i]

        ref_avg   = sum(counts[ref_start:ref_end]) / (ref_end - ref_start)
        threshold = ref_avg * 0.70

        if ref_avg == 0:
            print(f"    {months[i]}: zero reference average, accepting")
            return months[i]

        pct    = counts[i] / ref_avg * 100
        status = "COMPLETE" if counts[i] >= threshold else "incomplete"
        print(f"    {months[i]}: {counts[i]:,} filings ({pct:.0f}% of {ref_avg:.0f} avg) → {status}")

        if counts[i] >= threshold:
            return months[i]

    fallback = months[max(0, len(months) - 3)]
    print(f"  No month met completeness threshold, using fallback: {fallback}")
    return fallback


def update_frontend_config(max_date: str):
    """
    Update MAX_DATE and DEFAULT_DATE in frontend JavaScript config files.

    MAX_DATE:     the latest complete month of data
    DEFAULT_DATE: 12 months prior to MAX_DATE (default slider position on load)

    Updates js/config.template.js, js/config.dev.js, and js/config.js.
    """
    max_dt       = datetime.strptime(max_date, '%Y-%m')
    default_dt   = max_dt.replace(year=max_dt.year - 1)
    default_date = default_dt.strftime('%Y-%m')

    print(f"  MAX_DATE:     {max_date}")
    print(f"  DEFAULT_DATE: {default_date}")

    config_files = [
        PROJECT_ROOT / "js" / "config.template.js",
        PROJECT_ROOT / "js" / "config.dev.js",
        PROJECT_ROOT / "js" / "config.js",
    ]

    for config_path in config_files:
        if not config_path.exists():
            print(f"  Skipping (not found): {config_path.name}")
            continue

        with open(config_path, 'r') as f:
            content = f.read()

        updated = re.sub(r"(MAX_DATE:\s*')[^']*(')",     f"\\g<1>{max_date}\\g<2>",     content)
        updated = re.sub(r"(DEFAULT_DATE:\s*')[^']*(')", f"\\g<1>{default_date}\\g<2>", updated)

        if updated != content:
            with open(config_path, 'w') as f:
                f.write(updated)
            print(f"  Updated {config_path.name}: MAX_DATE={max_date}, DEFAULT_DATE={default_date}")
        else:
            print(f"  No changes needed: {config_path.name}")


# =============================================================================
# SUPABASE UPLOAD
# =============================================================================

def push_to_supabase(aggregated_data: dict) -> bool:
    """
    Push aggregated data to Supabase tables.

    Tables:
    - evictions-tract:  Tract-level aggregations
    - evictions-hex:    Hexagon-level aggregations
    - evictions-school: School-level aggregations
    - evictions-city:   City-level aggregations
    - evictions-county: County-level aggregations (for trends chart)

    Returns True if all uploads succeeded, False if any errors occurred.
    """
    print("\n" + "=" * 60)
    print("PUSHING TO SUPABASE")
    print("=" * 60)

    if SKIP_SUPABASE:
        print("  Supabase upload SKIPPED (SKIP_SUPABASE=True)")
        print("  Set SKIP_SUPABASE=False when ready to upload")
        return True

    if not SUPABASE_URL or not SUPABASE_KEY:
        print("  ERROR: Supabase credentials not configured!")
        print("  Set SUPABASE_URL and SUPABASE_KEY in the .env file")
        return False

    supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)
    all_succeeded = True

    table_mapping = {
        'tracts':   'evictions-tract',
        'hexagons': 'evictions-hex',
        'schools':  'evictions-school',
        'cities':   'evictions-city',
        'counties': 'evictions-county',
    }

    # tract_id → tractid for Supabase schema compatibility
    column_mapping = {
        'tracts': {'tract_id': 'tractid'},
    }

    for data_type, table_name in table_mapping.items():
        if data_type not in aggregated_data:
            continue

        df = aggregated_data[data_type].copy()
        print(f"\n  Uploading to {table_name}: {len(df):,} rows")

        if data_type in column_mapping:
            df = df.rename(columns=column_mapping[data_type])

        # Sanitize NaN/inf before JSON serialization
        df = df.replace([float('inf'), float('-inf')], None)
        df = df.where(pd.notna(df), None)

        records = df.to_dict('records')
        for record in records:
            record['id'] = str(uuid.uuid4())
            for key, value in record.items():
                if isinstance(value, float) and (math.isnan(value) or math.isinf(value)):
                    record[key] = None

        # Delete all existing rows, then insert fresh data
        print(f"    Deleting existing data from {table_name}...")
        try:
            supabase.table(table_name).delete().neq('id', '00000000-0000-0000-0000-000000000000').execute()
            print(f"    Deleted successfully")
        except Exception as e:
            print(f"    WARNING: Could not delete existing data: {e}")
            all_succeeded = False

        # Insert in batches
        batch_size    = 1000
        total_uploaded = 0
        for i in range(0, len(records), batch_size):
            batch = records[i:i + batch_size]
            try:
                supabase.table(table_name).insert(batch).execute()
                total_uploaded += len(batch)
                print(f"    Batch {i // batch_size + 1}: {len(batch)} records inserted")
            except Exception as e:
                print(f"    ERROR on batch {i // batch_size + 1}: {e}")
                all_succeeded = False

        print(f"    Total uploaded: {total_uploaded:,}")

    return all_succeeded


# =============================================================================
# GIT COMMIT AND PUSH
# =============================================================================

def git_commit_and_push(max_date: str):
    """
    Stage js/config.template.js, commit, and push to remote.

    data-hidden/ is gitignored, so this commit only captures the MAX_DATE
    update in config.template.js — a small, meaningful change.
    """
    print("\n" + "=" * 60)
    print("GIT COMMIT AND PUSH")
    print("=" * 60)

    try:
        # Stage config files (config.js is the production file served by GitHub Pages)
        result = subprocess.run(
            ['git', 'add', 'js/config.template.js', 'js/config.js'],
            cwd=PROJECT_ROOT, capture_output=True, text=True
        )
        if result.returncode != 0:
            print(f"  ERROR: git add failed: {result.stderr.strip()}")
            return

        # Check if there's anything to commit
        result = subprocess.run(
            ['git', 'diff', '--cached', '--quiet'],
            cwd=PROJECT_ROOT, capture_output=True
        )
        if result.returncode == 0:
            print("  No changes to commit (config was already up to date)")
            return

        # Commit
        commit_msg = f"data: update MAX_DATE to {max_date}"
        result = subprocess.run(
            ['git', 'commit', '-m', commit_msg],
            cwd=PROJECT_ROOT, capture_output=True, text=True
        )
        if result.returncode != 0:
            print(f"  ERROR: git commit failed: {result.stderr.strip()}")
            return
        print(f"  Committed: {commit_msg}")

        # Push
        result = subprocess.run(
            ['git', 'push'],
            cwd=PROJECT_ROOT, capture_output=True, text=True
        )
        if result.returncode != 0:
            print(f"  ERROR: git push failed: {result.stderr.strip()}")
            print("  Push manually: git push")
            return
        print("  Pushed to remote successfully")

    except FileNotFoundError:
        print("  ERROR: git not found in PATH")


# =============================================================================
# MAIN EXECUTION
# =============================================================================

def main():
    print("=" * 60)
    print("EVICTION DATA COMPILER")
    print(f"Started: {datetime.now()}")
    print("=" * 60)

    # Step 1: Load and compile Eviction Lab data
    el_df = load_eviction_lab_data()

    if el_df.empty:
        print("\nERROR: No data loaded.")
        print("Place EL parquet or raw EL CSVs in the From_EL/ directory.")
        return

    # Step 2: Perform spatial joins
    joined_df = perform_spatial_joins(el_df)

    # Step 3: Load ROcc data for filing rate calculation
    rocc_data = load_rocc_data()

    # Step 4: Aggregate by geography
    aggregated = aggregate_by_geography(joined_df, rocc_data)

    # Step 5: Determine latest complete month
    print("\n" + "=" * 60)
    print("DETERMINING LATEST COMPLETE MONTH")
    print("=" * 60)
    max_date = determine_max_date(aggregated)
    print(f"\n  MAX_DATE: {max_date}")

    # Step 6: Update frontend config files
    print("\n" + "=" * 60)
    print("UPDATING FRONTEND CONFIG")
    print("=" * 60)
    update_frontend_config(max_date)

    # Step 7: Push to Supabase
    supabase_ok = push_to_supabase(aggregated)

    # Step 8: Commit and push config update (only if Supabase succeeded)
    if supabase_ok:
        git_commit_and_push(max_date)
    else:
        print("\n  WARNING: Skipping git push due to Supabase errors above.")
        print("  Fix errors, then manually run:")
        print("    git add js/config.template.js && git commit -m 'data: update MAX_DATE' && git push")

    # Summary
    print("\n" + "=" * 60)
    print("COMPILATION COMPLETE")
    print("=" * 60)
    print(f"\nSummary:")
    print(f"  Total records: {len(el_df):,}")
    for geo_type, agg_df in aggregated.items():
        print(f"  {geo_type.title():10s}: {len(agg_df):,} rows")
    print(f"  MAX_DATE:     {max_date}")
    print(f"  Supabase:     {'OK' if supabase_ok else 'ERRORS (see above)'}")
    print(f"\nCompleted: {datetime.now()}")


if __name__ == "__main__":
    main()
