name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Generate production config
        run: |
          # Use environment variables to avoid sed issues with special characters
          cat js/config.template.js | \
          sed "s|\${SUPABASE_URL}|${{ secrets.SUPABASE_URL }}|g" | \
          sed "s|\${SUPABASE_ANON_KEY}|${{ secrets.SUPABASE_ANON_KEY }}|g" | \
          sed "s|\${MAPBOX_ACCESS_TOKEN}|${{ secrets.MAPBOX_ACCESS_TOKEN }}|g" \
          > js/config.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          exclude_assets: ".github,*.md,.gitignore,js/config.template.js,js/config.dev.js"
